syntax = "proto3";
package com.abolfazlMokhtari.pounes.proto;

message Users {
   repeated User users = 1;
}

message User {
  string _id = 1;
  int64 telegramId = 2;
  string fullName = 3;
  int32 age = 4;
  string gender = 5;
  string lookingFor = 6;
  string country = 7;
  string state = 8;
  string flag = 9;
  string language = 10;
  int64 lastSeen = 11;
  int64 lastUpdate = 12;
  bool sleep = 13;
  string education = 14;
  string dietaryPreference = 15;
  string job = 16;
  string workout = 17;
  string sleepingHabits = 18;
  string pets = 19;
  string bio = 20;
  int32 score = 21;
  repeated string profileImages = 22;
  string inviteCode = 23;
}



